### ISSUE TITLE
SVXplorer pip install errors

### ISSUE THREAD

**Issue by ghost** [kunalkathuria/SVXplorer#93]
Hello, 
On Ubuntu 18.04 running 

```
sudo pip install -r requirements.txt
```
runs into 

```
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/urbe/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python_version>'2.6'
  Downloading python_version-0.0.2-py2.py3-none-any.whl (3.4 kB)
Collecting bitarray==1.0.1
  Downloading bitarray-1.0.1.tar.gz (37 kB)
Collecting decorator==4.4.0
  Downloading decorator-4.4.0-py2.py3-none-any.whl (8.3 kB)
Collecting interlap==0.2.6
  Downloading interlap-0.2.6.tar.gz (6.0 kB)
Collecting logging==0.4.9.6
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     |████████████████████████████████| 96 kB 13.8 MB/s 
Collecting networkx==2.2
  Downloading networkx-2.2.zip (1.7 MB)
     |████████████████████████████████| 1.7 MB 21.2 MB/s 
Collecting numpy==1.16.5
  Downloading numpy-1.16.5.zip (5.1 MB)
     |████████████████████████████████| 5.1 MB 24.9 MB/s 
Collecting pandas==0.24.2
  Downloading pandas-0.24.2.tar.gz (11.8 MB)
     |████████████████████████████████| 11.8 MB 26.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/pypy -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-HesiyY/pandas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-HesiyY/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-HesiyY/pandas/pip-egg-info
         cwd: /tmp/pip-install-HesiyY/pandas/
    Complete output (50 lines):
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-install-HesiyY/pandas/setup.py", line 746, in <module>
        **setuptools_kwargs)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/pypy2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/pypy2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/pypy2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/pypy/lib-python/2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/pypy/lib-python/2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/pypy2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-gzQgr3/numpy-1.18.2/setup.py", line 32, in <module>
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sienkie** [comment]
Could you specify python and pip versions you are using?

**Comment by ghost** [comment]
pip 19.2.3, python 3.6

**Comment by kunalkathuria** [comment]
For the moment though, you can download tarball release or clone project using git. Thanks.

**Comment by kunalkathuria** [comment]
While we work on this, please download tarball release or clone project using git. Thanks.

**Comment by sienkie** [comment]
@aderzelle SVXplorer is an exclusively python2 package. 

The requirements.txt file right now only specifies python version > 2.6 which is why you were able to start the installation but not finish it. Thank you for catching this issue.

**Comment by ghost** [comment]
I could install it in a dedicated python 2.7 environment using conda, as well as the dependencies through conda.

**Comment by aakrosh** [comment]
Thanks. Another option (added here for posterity) is to use 'pip2 install -r requirements.txt', which forces use of python 2.
